name: coverage
on:
  push:
    branches: [main]
  pull_request:
jobs:
  test-and-badge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm run coverage
      - name: Generate coverage badge
        uses: emibcn/badge-action@v2
        with:
          label: coverage
          status: ${{ steps.cov.outputs.lines }}
          color: green
        id: badge
      - name: Extract coverage (lines %)
        id: cov
        run: |
          PCT=$(cat ./coverage/coverage-summary.json | node -e "let s='';process.stdin.on('data',d=>s+=d).on('end',()=>{const j=JSON.parse(s);console.log(j.total.lines.pct.toFixed(0)+'%')});")
          echo "lines=$PCT" >> $GITHUB_OUTPUT
      - name: Commit badge
        run: |
          mkdir -p .github/badges
          echo '${{ steps.badge.outputs.badge-svg }}' > .github/badges/coverage.svg
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github/badges/coverage.svg
          git commit -m "chore: update coverage badge [skip ci]" || echo "no changes"
          git push
